version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd frontend-react && npm install
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd frontend-react && npm install && npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
