version: 2
jobs:
 
  backend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd backend-express && npm install && npm run ci
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
